### ISSUE TITLE
allow custom CURLY regexp?

### ISSUE THREAD

**Issue by paulovieira** [lukeed/tempura#5]
Another awesome tiny library! Thanks for sharing. I'm an old-schooler who still uses underscore.js when a simple template system is needed. This library seems to be a perfect replacement.

One simple improvement (but with large potential, I think): allow the CURLY regexp to be set in the options. Users could then use single curly braces (a la svelte, react, etc).

Example:

```js
let templateStr = `

{#expect foo}

<div>hello {foo}</div>
`

let options = { 
    curly: /{{?\s*([\s\S]*?)\s*}}?/g 
};

let templateFn = tempura.compile(templateString, options);
let output = templateFn({ foo: 'world' })
```

**Comment by lukeed** [comment]
Hey, thank you

TBH I'm leaning against this. While I understand the use case for it, I think it adds extra code for it to work correctly – and, more importantly, limits the safety in what assumptions I can make down the road. As it is, the entire syntax will flat-out break if a `options.curly` is wrong. Obviously, in saying that, it sounds like user error, but it's never _actually_ obvious that's the case when you're the user. 

Stuff like [raw values](https://github.com/lukeed/tempura/blob/master/src/%24utils.js#L87), comments, and possible custom, non-child blocks (via #3) all become a giant question mark as soon as you define a custom curly pattern.

**Comment by paulovieira** [comment]
> I think it adds extra code for it to work correctly – and, more importantly, limits the safety in what assumptions I can make down the road. As it is, the entire syntax will flat-out break if a options.curly is wrong.

I was assuming that everything would work by just using a different regexp, but that's obviously not the case.

You're right. Tempura is meant to be small and simple. This kind of configurations won't help with that objective.
