### ISSUE TITLE
`initials` variable in `gen` not correct

### ISSUE THREAD

**Issue by tuanddd** [lukeed/tempura#7]
First of all, thank you for a great library! 🙂

This is a really weird bug, I don't know the reason why it turned out like that and whether @lukeed or others have bumped into it.

The `tmp` variable in the `gen` function is not being assigned correctly due to the expression `[...initials].join()` evaluating to `[object Set]` and not the actual list of prop names.

Unfortunately, as I don't know the reason why it behaves that way so I can't provide a reproducible example.

My guess is that somehow the default toString is being called while in the template literal so my suggestion would be to extract the `[...initials],join()` bit to be its own separate variable assignment.

[The video (if it helps)](https://www.loom.com/share/5ebde126ba9849298f5cecea1c962ea7)

**Comment by lukeed** [comment]
Hey, thanks :)

Can you start by providing the options you passed to transfo/compile? We can go from there.

Thanks!

**Comment by tuanddd** [comment]
Oh yeah sorry, I used the following code (list of props is simplified):

```js
compile("{{ url }}", { props: ["url"] })
```

**Comment by lukeed** [comment]
Hmm.. that's fairly basic. I think it might depend on the runtime that you're running this in? 

I added tests that show it's working as expected – as I can replicate that in my installed browsers and a few Node versions.

Where are you trying to run this? Please include node and/or browser version :) Thanks!

**Comment by tuanddd** [comment]
Hey,

I'm using it in the browser with ChromeVersion 92.0.4515.107 and Node 14.17.3

**Comment by lukeed** [comment]
Thanks. Something else is going on then.

That's the same [Node version](https://github.com/lukeed/tempura/runs/3158049269#step:3:6) that the CI suite uses.
And I'm on the same Chrome version:

<img width="447" alt="Screen Shot 2021-07-26 at 7 32 27 PM" src="https://user-images.githubusercontent.com/5855893/127085895-4251af55-5b7f-42bf-b4c4-8650f4a50be2.png">
<img width="821" alt="Screen Shot 2021-07-26 at 7 33 02 PM" src="https://user-images.githubusercontent.com/5855893/127085903-560468a8-3ea5-42db-be27-f62b4454748a.png">

My guess is you have some kind of `Set` polyfill running that you don't need & shouldn't be there. A correct polyfill wouldn't be causing this issue anyway, though
